### ISSUE TITLE
Doppelte Vorschläge

### ISSUE THREAD

**Issue by ic-hv** [europace/baufismart-finanzierungsvorschlaege-api#7]
Manchmal werden Finanzierungsvorschläge doppelt ausgeliefert. Hierzu ein paar Screenshots aus einer Debug-Session. Die Finanzierungsvorschläge Nr. 64 und Nr. 66 sind gleich - einziger Unterschied die "Kennung" (rot eingekringelt).

![snip1](https://user-images.githubusercontent.com/26538616/51175461-b91a4100-18ba-11e9-9f87-a4e021e2a4e8.png)

![snip2](https://user-images.githubusercontent.com/26538616/51175463-b9b2d780-18ba-11e9-9bbb-0f003a915316.png)

![snip3](https://user-images.githubusercontent.com/26538616/51175465-b9b2d780-18ba-11e9-8e2e-1265c8684115.png)

**Comment by caspii** [comment]
das ist die Angebotskennung, die kann muss aber nicht bei weiteren Produktabbildungen der Masterproduzenten gesetzt sein.

Das kann eine Aktion sein, Prolongation oder für bestimmte Vertriebe ein besonderes Produkt etc. Was jetzt genau hinter dem Produkt " Gestehung100" steht müsste Genopace wissen. Sollen wir dem nachgehen

**Comment by ic-hv** [comment]
Meinerseits ist ein Nachgehen nicht notwendig, ich filtere auf meiner Seite "gleiche" Vorschläge eh' heraus - dachte nur das es für Europace interessant wäre zu wissen ... weil ja trotz allem ein wenig Bandbreite verschenkt wird, wenn doppelte Finazierungsvorschläge rausgehen (ob der eine jetzt die Kennung "abc" und der andere die Kennung "xyz" hat - dürfte dem am Vorschlag Interessierten ja wohl eher "Wurscht" sein)
